<?php
/**
 * calendar/decide.php
 *
 * Approve/reject endpoint hit by links in the weekly digest email.
 * URL format:  /calendar/decide.php?token=XXX&id=YYY&action=approve|reject
 *
 * - Loads queue/digest-latest.json
 * - Verifies the token matches the one stored for that proposal id
 * - Moves the item into queue/approved-queue.json (approve) or
 *   queue/rejected.json (reject), and removes it from digest-latest.json
 *   so the same click can't be replayed
 * - Returns a small HTML confirmation page
 *
 * The scheduled agent's next run drains approved-queue.json and posts
 * each event to Christopher's Public Events Google Calendar.
 *
 * NOTE: token is per-proposal, generated by the agent when building the
 * digest. It's single-use by construction — once consumed, the proposal
 * is removed from digest-latest.json.
 */
declare(strict_types=1);

const QUEUE_DIR = __DIR__ . '/queue';
const DIGEST    = QUEUE_DIR . '/digest-latest.json';
const APPROVED  = QUEUE_DIR . '/approved-queue.json';
const REJECTED  = QUEUE_DIR . '/rejected.json';

$token  = $_GET['token']  ?? '';
$id     = $_GET['id']     ?? '';
$action = $_GET['action'] ?? '';

if (!in_array($action, ['approve', 'reject'], true) || $token === '' || $id === '') {
    respond('Invalid request', 'Missing or invalid token, id, or action.', 400);
}

if (!is_dir(QUEUE_DIR) || !is_writable(QUEUE_DIR)) {
    respond('Server setup issue', 'The queue directory is missing or not writable. Ask Claude to check Dreamhost file permissions on calendar/queue/.', 500);
}

// Advisory-locked read of digest-latest.json (hold the lock through
// the write at the end — we want the digest update to be the LAST
// step so a mid-flow crash can't leave the proposal orphaned).
$fp = fopen(DIGEST, 'c+');
if (!$fp) respond('Could not open digest', 'digest-latest.json unreadable.', 500);
flock($fp, LOCK_EX);
$raw = stream_get_contents($fp);
$digest = $raw ? json_decode($raw, true) : null;
if (!is_array($digest) || !isset($digest['proposals']) || !is_array($digest['proposals'])) {
    flock($fp, LOCK_UN); fclose($fp);
    respond('No active digest', 'The current digest is empty or malformed. This usually means the proposal has already been acted on, or a new digest hasn\'t run yet.', 404);
}

$found = null;
$remaining = [];
foreach ($digest['proposals'] as $p) {
    if (($p['id'] ?? null) === $id) { $found = $p; continue; }
    $remaining[] = $p;
}

if ($found === null) {
    flock($fp, LOCK_UN); fclose($fp);
    respond('Already acted on', 'That proposal is no longer in the current digest — it may have been approved, rejected, or rolled over already.', 410);
}

if (!hash_equals((string)($found['token'] ?? ''), $token)) {
    flock($fp, LOCK_UN); fclose($fp);
    respond('Invalid token', 'Token does not match. If you\'re using an old digest email, this is expected.', 403);
}

// Write destination FIRST. If this fails, the digest stays intact and
// the user can retry the approve/reject click safely. (Previously we
// removed from digest first and lost the proposal entirely on a
// destination-write failure.)
$dest = $action === 'approve' ? APPROVED : REJECTED;
$fp2 = fopen($dest, 'c+');
if (!$fp2) {
    flock($fp, LOCK_UN); fclose($fp);
    respond('Could not open destination queue', $dest, 500);
}
flock($fp2, LOCK_EX);
$raw2 = stream_get_contents($fp2);
$doc  = $raw2 ? json_decode($raw2, true) : null;
if (!is_array($doc) || !isset($doc['events']) || !is_array($doc['events'])) {
    $doc = ['_note' => ($action === 'approve' ? 'approval queue' : 'rejection log'), 'events' => []];
}

$now = date(DATE_ATOM);
if ($action === 'approve') {
    $payload = $found;
    unset($payload['token']);
    $payload['approved_at']  = $now;
    $payload['approved_via'] = 'decide.php';
    $doc['events'][] = $payload;
} else {
    $doc['events'][] = [
        'id'          => $found['id'] ?? null,
        'title'       => $found['title'] ?? '(untitled)',
        'rejected_at' => $now,
        'reason'      => null,
    ];
}

ftruncate($fp2, 0);
rewind($fp2);
$wrote = fwrite($fp2, json_encode($doc, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
fflush($fp2);
flock($fp2, LOCK_UN);
fclose($fp2);
if ($wrote === false) {
    // Destination failed; digest untouched — user can retry the click.
    flock($fp, LOCK_UN); fclose($fp);
    respond('Save failed', 'Could not persist your decision. Click the link again to retry.', 500);
}

// Destination committed — now remove the proposal from the digest.
$digest['proposals'] = $remaining;
ftruncate($fp, 0);
rewind($fp);
fwrite($fp, json_encode($digest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE));
fflush($fp);
flock($fp, LOCK_UN);
fclose($fp);

// Confirmation page
$title = htmlspecialchars($found['title'] ?? '(untitled)', ENT_QUOTES, 'UTF-8');
if ($action === 'approve') {
    respond(
        'Approved',
        "\"$title\" is queued.<br>It will be posted to your Public Events Google Calendar on the next scheduled agent run.<br>The site picks it up from there.",
        200
    );
} else {
    respond('Rejected', "\"$title\" won't be proposed again.", 200);
}

// ──────────────────────────────────────────────────────────────────────
function respond(string $title, string $body, int $code): void {
    http_response_code($code);
    header('Content-Type: text/html; charset=utf-8');
    $t = htmlspecialchars($title, ENT_QUOTES, 'UTF-8');
    echo <<<HTML
<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>$t — chriso.org calendar</title>
<style>
  body { background:#081818; color:#ede3c8; font-family:'Courier New',monospace;
         min-height:100vh; display:flex; align-items:center; justify-content:center; padding:40px; }
  .card { max-width:520px; text-align:center; }
  h1 { font-size:1.8rem; letter-spacing:0.04em; margin-bottom:18px;
       color:#f2d8dd; font-weight:700; }
  p { line-height:1.7; color:rgba(237,227,200,0.75); font-size:0.95rem; }
  a { color:#dccfae; }
</style></head><body>
<div class="card">
  <h1>$t</h1>
  <p>$body</p>
  <p style="margin-top:28px;"><a href="/calendar/">← back to calendar</a></p>
</div>
</body></html>
HTML;
    exit;
}
